source "https://rubygems.org"

ruby File.read(".ruby-version").strip

gem "bootsnap"
gem "puma"
gem "rails", "6.1.1"
gem "sass-rails"

group :development, :test do
  gem "rubocop-govuk"
  gem "simplecov"
end

group :development do
  gem "flog"
  gem "listen"
  gem "spring"
end

group :test do
  gem "capybara"
  gem "rspec-rails"
end
