source "https://rubygems.org"

ruby File.read(".ruby-version").strip

gem "bootsnap"
gem "pg"
gem "puma"
gem "rails", "6.1.1"

group :development, :test do
  gem "rubocop-govuk"
  gem "simplecov"
end

group :development do
  gem "listen"
  gem "spring"
end

group :test do
  gem "rspec-rails"
end
